
# update options
[update]

# how frequent to check for updates
frequency = "daily"

# what folders/files to protect from deletion
protected = [
    "data/*.json"
]

# the url of the update service to checkin with
service = "http://somewhere.com"

postupdate = [
    "npm install",
    "npm prune"
]

# startup options
[startup]

#command to run on startup
command = "node server.js"
